### ISSUE TITLE
Stacking of error messages in Login & Registration

### ISSUE THREAD

**Issue by alanj1998** [PAKDProject/Login_Register_Page#2]
<img width="1920" alt="screenshot 2018-10-18 at 15 40 00" src="https://user-images.githubusercontent.com/25364332/47162592-246c6b00-d2ec-11e8-94ba-cfd0931fbd89.png">

Look at .empty() for external div before it is created!

**Comment by alanj1998** [comment]
Good Job Paul!

**Comment by Paul-Kratz** [comment]
<h2>IM GETTING TO IT ALAN</h2>

**Comment by alanj1998** [comment]
fixed
