### ISSUE TITLE
Keeping the messages OG real

### ISSUE THREAD

**Issue by alanj1998** [PAKDProject/Login_Register_Page#8]
<img width="1920" alt="screenshot 2018-10-22 at 16 34 35" src="https://user-images.githubusercontent.com/25364332/47302121-97415300-d618-11e8-98d5-87ab71e907f6.png">

**Comment by Paul-Kratz** [comment]
<h3>I don't see the problem really &#9968;</h3>

**Comment by Paul-Kratz** [comment]
If someone doesnt understand isnt it really <b>their</b> problem
